---
metrics:
  - name: oci_all_lb_bytesent
    help: "The number of bytes sent from all load balancer."
    type: many
    interval: 3
    namespace: oci_lbaas
    mql: BytesSent[1m].mean()
    compartmentId: ocid1.compartment.oc1..aaaaaaaahr7aicqtodxmcfor6pbqn3hvsngpftozyxzqw36gj4kh3w3kkj4q
    label1: dev
    label2: high
  - name: oci_vm1_mem
    help: "vm1 mem usage."
    type: single
    interval: 1
    namespace: oci_computeagent
    mql: MemoryUtilization[1m]{resourceId = "ocid1.instance.oc1.ap-singapore-1.anzwsljrak7gbriccijo42npujwjrub3j6e6fkoe7ijtpcn4krhndgr3f2da"}.mean()
    compartmentId: ocid1.compartment.oc1..aaaaaaaahr7aicqtodxmcfor6pbqn3hvsngpftozyxzqw36gj4kh3w3kkj4q
    label1: dev
    label2: high
#  - name: oci_vm_mem
#    help: "oci mem usgae ."
#    type: single
#    interval: 1
#    namespace: oci_computeagent
#    mql: DiskIopsWritten[1m]{resourceId = "ocid1.instance.oc1.ap-singapore-1.anzwsljrak7gbriccijo42npujwjrub3j6e6fkoe7ijtpcn4krhndgr3f2da"}.rate()
#    label:
#      a: b